POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user2",
  "password": "password"
}


> {% client.global.set("auth_token", response.body) %}
###

GET http://localhost:8080/todo/1
Authorization: Bearer {{auth_token}}

###

GET http://localhost:8080/admin/test
Authorization: Bearer {{auth_token}}

###